### ISSUE TITLE
Add "solve" variant that takes function

### ISSUE THREAD

**Issue by nibe** [timothypratley/munkres#2]
It'd be nice if there was a `solve` variant that takes a function instead of a matrix:

```
(defn minimize-weight [f agents tasks]
  "Assigns tasks to agents, minimising the weight calculated by f."
  (->> f
    (weight-matrix agents tasks)
    (solve agents tasks)))
```

`f` should be the first argument so that it works well with [partial](https://clojuredocs.org/clojure.core/partial).

**Comment by timothypratley** [comment]
Great idea, I agree... I can take a look into it on the weekend;
also pull requests are welcome :)
